name: web_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  google_fonts: 2.1.1
  flutter_svg: ^1.0.3
  settings_ui: ^2.0.2
  lottie: ^1.3.0
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  uuid: ^3.0.6
  supabase_flutter: ^0.3.1
  get_it: ^7.2.0
  syncfusion_flutter_xlsio: ^20.1.57-beta
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/

